### ISSUE TITLE
Point within bounding box?

### ISSUE THREAD

**Issue by getify** [davidwood/node-geopoint#6]
I wanted to check if a point was within a bounding box centered on another point. This is what I've come up with so far:

```js
function withinBoundingBox(point,center,dist) {
	var [nePoint,swPoint] = center.boundingCoordinates(dist);
	return !(
		point.latitude() < Math.min(nePoint.latitude(),swPoint.latitude()) ||
		point.longitude() < Math.min(nePoint.longitude(),swPoint.longitude()) ||
		point.latitude() > Math.max(nePoint.latitude(),swPoint.latitude()) ||
		point.longitude() > Math.max(nePoint.longitude(),swPoint.longitude())
	);
}
```

In my small scale test on known points in my own neighborhood (in the US), it seems to work. But I confess that I don't really understand lat/long well enough to validate if it works correctly in all other places.

So my first question is, is this correct, or am I missing something?

Secondly, would a function like this be useful for this library, like as a method on a point?

**Comment by lspellman** [comment]
I know it's almost a year later, but this module is supposedly derived from this paper: http://janmatuschek.de/LatitudeLongitudeBoundingCoordinates.  Based on the formula he describes there, I think you would have some points that would "pass" the test, but actually be a false result. This would occur in the corners of the square bounding box, where the edge of the circle is only equal to the edge of the bounding box at the N,S,E,W boundaries.

**Comment by getify** [comment]
To be clear, I wasn't trying to find points within a certain distance of a center point... I know that would be circular. I wanted all points within a rectangular bounding box with the given point at its center.

The logic there is similar to what we use for determining points within a bounding box on a 2-d flat axes-grid. My question was whether there were corner cases with the math of latitude / longitude that would cause those assumptions to fail.
